--
-- Database: `albums`
--

-- --------------------------------------------------------

--
-- Table structure for table `albums`
--

CREATE TABLE `albums` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `artist` varchar(255) NOT NULL,
  `price` int(255) NOT NULL,
  `number_of_track` int(255) NOT NULL,
  `image_id` int(255) NOT NULL,
 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `albums`
--

INSERT INTO `albums` (`id`, `name`, `artist`, `price`, `number_of_track`, `image_id`) VALUES
(1, 'Coachella', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'USA', '2020-12-31', 1),
(2, 'Tomorrowland', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Belgium', '2021-10-28', 2),
(3, 'Burning Man', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'USA', '2021-02-21', 3),
(4, 'Rock in Rio', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Brazil', '2020-04-29', 4),
(5, 'Glastonbury', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'UK', '2020-08-10', 5),
(6, 'Creamfields', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'UK', '2021-05-12', 6),
(7, 'Time Warp', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Germany', '2020-08-25', 7),
(8, 'Reading album', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'UK', '2020-12-08', 8),
(9, 'Fuji Rock', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Japan', '2021-09-17', 9),
(10, 'Mysteryland', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Netherlands', '2020-11-14', 10),
(11, 'Sziget album', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Hungary', '2021-06-03', 11),
(12, 'Mawazine', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Morocco', '2021-10-04', 12),
(13, 'Primavera Sound', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim, vitae placerat lorem dapibus ut. Ut lacinia ultrices convallis. Nam tristique sapien sed mollis mattis. Donec at facilisis lacus. Cras condimentum rhoncus sem lacinia congue. Nam egestas vulputate ipsum, viverra vehicula diam rutrum nec. Quisque commodo vehicula urna vel vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vehicula ex vel risus rutrum sodales. Sed consequat augue ac dui ornare, at aliquet lectus interdum. Nullam sed erat eget ex eleifend sagittis. Vestibulum tristique, neque et cursus blandit, nisi justo hendrerit diam, a condimentum dolor lacus ac elit.\r\n\r\nSuspendisse non fringilla nunc. Vestibulum ornare quis sem eu sollicitudin. Nam porta, eros sed aliquet varius, sapien est tempus orci, eu fermentum tortor augue in tortor. Curabitur faucibus pellentesque accumsan. Sed nec magna ut quam consectetur rutrum ac quis ante. Quisque lectus lorem, malesuada a porta non, laoreet quis urna. Aliquam lorem leo, accumsan ut bibendum eget, venenatis ac diam. Curabitur feugiat diam interdum, mattis quam quis, suscipit purus. Nunc convallis rutrum elit ac pharetra. Nunc eu tellus venenatis, dapibus mauris at, dignissim elit. Aliquam consectetur, dolor eu rhoncus tristique, mauris risus suscipit dolor, eget pharetra dolor orci id neque. Aenean vel metus ac dolor semper consectetur nec tincidunt nisi. Mauris a purus augue. Maecenas id imperdiet urna, sit amet convallis ipsum.\r\n\r\nNulla facilisi. In sed urna quis nunc finibus porta. Pellentesque euismod turpis id sollicitudin pretium. Integer ante leo, efficitur sit amet ultrices ac, pulvinar varius sapien. In vel consectetur orci. Donec eu lacus eget diam pharetra laoreet. Morbi et consequat mi. Ut ut purus non sapien interdum luctus. Pellentesque sit amet vulputate dolor. Donec in imperdiet metus, vitae commodo magna. Fusce pharetra laoreet felis eu imperdiet. Pellentesque maximus nunc accumsan elit euismod molestie. Donec id erat dictum, vestibulum velit non, placerat leo.', 'Spain', '2021-08-15', 13),
(14, 'Osheaga ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim', 'Canada', '2021-07-18', 14),
(15, 'Ultra Europe', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim', 'Croatia', '2021-05-26', 15),
(16, 'Wanderland', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum nisl enim' , 'Philippines', '2021-07-01', 16);

-- --------------------------------------------------------

--
-- Table structure for table `images`
--

CREATE TABLE `images` (
  `id` int(11) NOT NULL,
  `filename` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `images`
--

INSERT INTO `images` (`id`, `filename`) VALUES
(1, 'assets/img/album_01.png'),
(2, 'assets/img/album_02.png'),
(3, 'assets/img/album_03.png'),
(4, 'assets/img/album_04.png'),
(5, 'assets/img/album_05.png'),
(6, 'assets/img/album_06.png'),
(7, 'assets/img/album_07.png'),
(8, 'assets/img/album_08.png'),
(9, 'assets/img/album_09.png'),
(10, 'assets/img/album_10.png'),
(11, 'assets/img/album_11.png'),
(12, 'assets/img/album_12.png'),
(13, 'assets/img/album_13.png'),
(14, 'assets/img/album_14.png'),
(15, 'assets/img/album_15.png'),
(16, 'assets/img/album_16.png');

-- --------------------------------------------------------

--
-- Indexes for dumped tables
--

--
-- Indexes for table `albums`
--
ALTER TABLE `albums`
  ADD PRIMARY KEY (`id`),
  ADD KEY `albums_image_fk` (`image_id`);

--
-- Indexes for table `images`
--
ALTER TABLE `images`
  ADD PRIMARY KEY (`id`);

-- --------------------------------------------------------

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `albums`
--
ALTER TABLE `albums`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT for table `images`
--
ALTER TABLE `images`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

-- --------------------------------------------------------

--
-- Constraints for dumped tables
--

--
-- Constraints for table `albums`
--
ALTER TABLE `albums`
  ADD CONSTRAINT `albums_image_fk` FOREIGN KEY (`image_id`) REFERENCES `images` (`id`);

-- --------------------------------------------------------